# Generated by Django 4.0 on 2021-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='firma klienta'),
        ),
    ]
